### ISSUE TITLE
using actions-find-and-replace-string to escape double quotes

### ISSUE THREAD

**Issue by woodie** [mad9000/actions-find-and-replace-string#1]
I need to stuff the `github.event.issue.title` into a GraphQL query to Monday.com.  The `column_value` is the `github.event.issue.title` which can contain double-quotes, that mess up the query. WHat's the proper way to do this?
```yml
      - id: title
        uses: mad9000/actions-find-and-replace-string@2
        with:
          source: ${{ github.event.issue.title }}
          find: '"' 
          replace: '\\\"'
```
